include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_control_body_on_new_line
    - always_specify_types
    - prefer_single_quotes
    - unnecessary_new
    - lines_longer_than_80_chars
