name: Deploy Dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Logos PNG files
      run: |
        shopt -s nullglob
        for file in $(find flutter_any_log/assets \( -path "flutter_any_log/assets/basketball/*" -o -path "flutter_any_log/assets/euroleague/*" -o -path "flutter_any_log/assets/fashion/*" -o -path "flutter_any_log/assets/food/*" -o -path "flutter_any_log/assets/football/*" -o -path "flutter_any_log/assets/media/*" -o -path "flutter_any_log/assets/tech/*" \) -type f ! -name "*.png"); do
          echo "ERROR: File '$file' is not a PNG file"
        done
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.5'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
      
    - name: Analyze Linting
      run: flutter analyze
